# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/void/repos/allennlp-recipes/pytorch-pretrained-bert, last modified Wed Nov 20 19:28:29 2020
# ------------------------------------------------

package:
    name: pytorch-pretrained-bert
    version: 0.6.2

build:
    entry_points:
        - pytorch-pretrained-bert = pytorch_pretrained_bert.__main__:main
        - pytorch_pretrained_bert = pytorch_pretrained_bert.__main__:main
    number: '0'
    script: /home/void/.miniconda3/envs/build/conda-bld/pytorch-pretrained-bert_1574296147238/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps -vv
    string: py37_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py37_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py37_0
        - python 3.7.5 h0371630_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py37_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py37_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - boto3
        - numpy
        - python >=3.7,<3.8.0a0
        - regex
        - requests
        - tqdm
test:
    imports:
        - pytorch_pretrained_bert
    requires:
        - pytorch-cpu
about:
    description: "This repository contains op-for-op PyTorch reimplementations, pre-trained\n\
        models and fine-tuning examples for:\n  - Google's BERT model,\n  - OpenAI's\
        \ GPT model,\n  - Google/CMU's Transformer-XL model, and\n  - OpenAI's GPT-2\
        \ model.\nThese implementations have been tested on several datasets (see\
        \ the\nexamples).\n"
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: PyTorch version of Google AI BERT model with script to load Google pre-trained
        models
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - CurtLH
        - sodre
